/**
 * Compose the mark and the name into a single lockup file.
 *
 *   node scripts/build-lockup.mjs                 # every wordmark in design/wordmarks/
 *   node scripts/build-lockup.mjs nunito          # just one
 *
 * WHY THIS IS ONE FILE AND NOT TWO ELEMENTS
 *
 * Composed live from an SVG next to a text node, the gap between them depends on the reader's font metrics and the name renders in whatever face they happen to have — so the app header, a link preview and a printed flyer would each look slightly different. Baking the spacing into one file removes the question.
 *
 * The name arrives from design/wordmarks/<face>.json as path coordinates, outlined once by scripts/outline-wordmark.py. No font is read here, none is downloaded, and none is shipped.
 *
 * The mark geometry is imported from mark.mjs rather than copied, so the lockup cannot drift out of sync with the icons — which is the failure mode Graftful documents a manual workaround for.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ACCENT, PIVOT, TILT, body, bounds } from './mark.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const wordDir = join(root, 'design', 'wordmarks');
const outDir = join(root, 'static');

const n = (v) => Number(v.toFixed(2));

/**
 * Proportions, all expressed against the font's x-height.
 *
 * x-height rather than cap height because "coruja" is set lowercase and has neither capitals nor ascenders — its own ink cannot say how big a capital would have been, so cap height is not available to reference. x-height is, it comes from the font's OS/2 table rather than from this particular word, and it means the mark keeps the same size whether the C is capitalised or not. Sizing against the word's bounding box would be worse still: the j's descender would decide how large the owl is.
 *
 * GAP was 0.16 of cap height and is now 0.40 of x-height — roughly 1.7× wider, which is the "a bit more space" this is meant to be. Wide enough to breathe, still tight enough to read as one lockup rather than an icon standing next to a word.
 */
const MARK_TO_X = 1.6; // the mark stands well above the x-height letters
const GAP_TO_X = 0.4;
const PAD_TO_X = 0.14;

function compose({ wordD, box, provenance, xHeight, text }, { ink, ground }) {
	// Font space after the Y-flip: baseline at 0, ink above baseline is negative y.
	const wordW = box.x2 - box.x1;

	const markBox = bounds();
	const markH = xHeight * MARK_TO_X;
	const scale = markH / (markBox.y2 - markBox.y1);
	const markW = (markBox.x2 - markBox.x1) * scale;

	const gap = xHeight * GAP_TO_X;
	const pad = xHeight * PAD_TO_X;

	// Centre the mark on the x-height band, so it sits optically level with the letter bodies. Descenders hang below that band by design and must not drag the mark down with them.
	const markTop = -xHeight / 2 - markH / 2;
	const markBottom = markTop + markH;

	// The canvas has to contain whichever of the two reaches further in each direction — with the mark at 1.6× x-height that is the mark above, and the j's tail below.
	const top = Math.min(markTop, box.y1);
	const bottom = Math.max(markBottom, box.y2);

	const totalW = pad * 2 + markW + gap + wordW;
	const totalH = pad * 2 + (bottom - top);

	// Shifting by -box.x1 puts the word's left edge exactly where intended rather than wherever the first glyph's sidebearing happened to leave it.
	const wordX = pad + markW + gap - box.x1;
	const wordY = pad - top;

	const markX = pad - markBox.x1 * scale;
	const markY = pad + (markTop - top) - markBox.y1 * scale;

	const inner = [
		ground ? `\t<rect width="${n(totalW)}" height="${n(totalH)}" fill="${ground}" />` : null,
		`\t<g transform="translate(${n(markX)} ${n(markY)}) scale(${n(scale)})">`,
		`\t\t<g transform="rotate(${TILT} ${PIVOT.x} ${PIVOT.y})">`,
		body(ink)
			.split('\n')
			.map((l) => '\t\t' + l)
			.join('\n'),
		`\t\t</g>`,
		`\t</g>`,
		`\t<path transform="translate(${n(wordX)} ${n(wordY)})" fill="${ink}" d="${wordD}" />`
	]
		.filter(Boolean)
		.join('\n');

	const svg =
		`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${n(totalW)} ${n(totalH)}" width="${Math.round(totalW)}" height="${Math.round(totalH)}" role="img" aria-label="${text}">\n` +
		`\t<!--\n` +
		`\t\tGENERATED by scripts/build-lockup.mjs. Do not edit by hand.\n\n` +
		`\t\tName outlined from ${provenance}.\n` +
		`\t\tOutlines only — no font file is read at build time or distributed with this project.\n\n` +
		`\t\tThe name is paths, not <text>, so this renders identically anywhere an SVG opens.\n` +
		`\t\tNever rebuild this lockup by placing the mark beside live text.\n` +
		`\t-->\n${inner}\n</svg>\n`;

	return { svg, totalW, totalH, markW, wordW, gap };
}

const only = process.argv[2];
const faces = readdirSync(wordDir)
	.filter((f) => f.endsWith('.json'))
	.map((f) => f.replace(/\.json$/, ''))
	.filter((f) => !only || f === only);

if (!faces.length) {
	console.error(`No wordmarks found in design/wordmarks/${only ? ` matching "${only}"` : ''}.`);
	console.error('Run scripts/outline-wordmark.py first.');
	process.exit(1);
}

mkdirSync(outDir, { recursive: true });
mkdirSync(join(root, 'design', 'lockups'), { recursive: true });

for (const face of faces) {
	const data = JSON.parse(readFileSync(join(wordDir, `${face}.json`), 'utf8'));

	const light = compose(data, { ink: ACCENT, ground: null });
	const dark = compose(data, { ink: '#ffffff', ground: ACCENT });

	// While candidates are still in the running the output lives in design/. Once one face and one casing are chosen, build that single one and it is written to static/ as the real lockup.svg and lockup-inverse.svg.
	const single = faces.length === 1;
	const dir = single ? outDir : join(root, 'design', 'lockups');
	const stem = single ? 'lockup' : `lockup-${face}`;

	writeFileSync(join(dir, `${stem}.svg`), light.svg);
	writeFileSync(join(dir, `${stem}-inverse.svg`), dark.svg);

	// The chosen lockup also lands in src, for the header's raw import; see build-marks.mjs.
	if (single) {
		const assetsDir = join(root, 'src', 'lib', 'assets');
		mkdirSync(assetsDir, { recursive: true });
		writeFileSync(join(assetsDir, 'lockup.svg'), light.svg);
	}

	console.log(
		`${face.padEnd(18)} ${String(Math.round(light.totalW)).padStart(5)} × ${String(Math.round(light.totalH)).padEnd(4)}` +
			`  ratio ${(light.totalW / light.totalH).toFixed(2)}:1` +
			`  mark ${Math.round(light.markW)}  gap ${Math.round(light.gap)}  word ${Math.round(light.wordW)}`
	);
}
